FROM golang:1.16-alpine3.12 AS builder

RUN go version

COPY . /downloader-music/
WORKDIR /downloader-music/

RUN go mod download
RUN GOOS=linux go build -o ./.bin/app ./cmd/app/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /downloader-music/.bin/app .
COPY --from=builder /downloader-music/configs .

EXPOSE 80

CMD ["./app"]