version: '3.4'

services:
  app:
    image: downloader-music
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
#    depends_on:
#      - mongodb
#    environment:
#
#    volumes:
#      - ./.bin/:/root/
#      - ./configs/:/root/configs/
#      - ./templates/:/root/templates/
    env_file:
      - .env